server:
  port: 8080   # Spring Boot 自己的 Web 端口 (如果你以后要加 REST API)

grpc:
  server:
    port: 9091   # gRPC 服务端口，BloomRPC 就连 localhost:9091

spring:
  datasource:
    url: jdbc:h2:file:./data/reports;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672

ai:
  evaluation-service:
    base-url: http://localhost:8085
  job-parser:
    base-url: http://localhost:8090
  resume-parser:
    base-url: http://localhost:8091
  interview-service:
    base-url: http://localhost:8092

supabase:
  project-url: ${SUPABASE_PROJECT_URL:https://project.supabase.co}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:}
  storage:
    public-url: ${SUPABASE_STORAGE_PUBLIC_URL:${supabase.project-url}/storage/v1/object/public}
    job-documents:
      name: ${SUPABASE_BUCKET_JOB_DOCUMENTS:job-documents}
      path-prefix: job-documents
    resumes:
      name: ${SUPABASE_BUCKET_RESUMES:resumes}
      path-prefix: resumes
    interview-audios:
      name: ${SUPABASE_BUCKET_INTERVIEW_AUDIOS:interview-audios}
      path-prefix: interview-audios
    profile-photos:
      name: ${SUPABASE_BUCKET_PROFILE_PHOTOS:profile-photos}
      path-prefix: profile-photos
