server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}

grpc:
  server:
    address: 0.0.0.0
    port: ${GRPC_SERVER_PORT:9091}
  client:
    usersvc:
      address: ${GRPC_CLIENT_USERSVC_ADDRESS:static://127.0.0.1:9091}
      negotiation-type: ${GRPC_CLIENT_USERSVC_NEGOTIATIONTYPE:PLAINTEXT}

spring:
  application:
    name: grpc-demo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres.ecqxglofqhtfkmjcgefi}
    password: ${SUPABASE_DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:chengcheng2zJ}}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672

ai:
  evaluation-service:
    base-url: http://localhost:8085
  job-parser:
    base-url: http://localhost:8090
  resume-parser:
    base-url: http://localhost:8091
  interview-service:
    base-url: http://localhost:8092

supabase:
  project-url: ${SUPABASE_PROJECT_URL:https://project.supabase.co}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY:}
  storage:
    public-url: ${SUPABASE_STORAGE_PUBLIC_URL:${supabase.project-url}/storage/v1/object/public}
    job-documents:
      name: ${SUPABASE_BUCKET_JOB_DOCUMENTS:job-documents}
      path-prefix: job-documents
    resumes:
      name: ${SUPABASE_BUCKET_RESUMES:resumes}
      path-prefix: resumes
    interview-audios:
      name: ${SUPABASE_BUCKET_INTERVIEW_AUDIOS:interview-audios}
      path-prefix: interview-audios
    profile-photos:
      name: ${SUPABASE_BUCKET_PROFILE_PHOTOS:profile-photos}
      path-prefix: profile-photos

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:*}
  auth:
    mode: ${APP_AUTH_MODE:supabase}
    env: ${APP_ENV:dev}
    supabase:
      project-url: ${SUPABASE_PROJECT_URL:https://project.supabase.co}
      jwks-url: ${SUPABASE_JWKS_URL:https://project.supabase.co/auth/v1/jwks}
    dev-otp:
      code: ${DEV_OTP_CODE:123456}
      jwt-secret: ${DEV_JWT_SECRET:change-me-please}
      jwt-expires-min: ${DEV_JWT_EXPIRES_MIN:1440}
      user-id: ${DEV_USER_ID:00000000-0000-0000-0000-000000000000}
      user-email: ${DEV_USER_EMAIL:dev@example.com}
  trial:
    mode: ${APP_TRIAL_MODE:dev-fixed}
    env: ${APP_ENV:dev}
    valid-days: ${TRIAL_VALID_DAYS:14}
    dev:
      code: ${DEV_TRIAL_CODE:EA-TRIAL-123456}
