server:
  address: 0.0.0.0
  port: 8080

grpc:
  server:
    port: 9091   # 暂用 9091，避免与旧的 5051 冲突；稳定后可改回 5051

app:
  mail:
    stub-enabled: true
  rabbit:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: postgres.ecqxglofqhtfkmjcgefi
    password: chengcheng2zJ
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties:
        sslmode: require
        preferQueryMode: simple
        prepareThreshold: 0

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  host: localhost
  port: 5672

ai:
  evaluation-service:
    base-url: http://localhost:8085
  job-parser:
    base-url: http://localhost:8090
  resume-parser:
    base-url: http://localhost:8091
  interview-service:
    base-url: http://localhost:8092
