server:
  port: 8080   # Spring Boot 自己的 Web 端口 (如果你以后要加 REST API)

grpc:
  server:
    port: 9091   # gRPC 服务端口，BloomRPC 就连 localhost:9091

spring:
  datasource:
    url: jdbc:h2:file:./data/reports;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672

ai:
  evaluation-service:
    base-url: http://localhost:8085
  job-parser:
    base-url: http://localhost:8090
  resume-parser:
    base-url: http://localhost:8091
  interview-service:
    base-url: http://localhost:8092
